### ISSUE TITLE
Type in ABAP-Library

### ISSUE THREAD

**Issue by raungkam** [keremkoseoglu/ABAP-Library#1]
Hello,
     How to know about type in your code?

**Comment by keremkoseoglu** [comment]
Hello @raungkam , ZBCD_CONV_EXIT_DIR is a data element type CHAR6. Possible values are included in the class:

    constants: c_dir_input  type zbcd_conv_exit_dir value 'INPUT',
               c_dir_output type zbcd_conv_exit_dir value 'OUTPUT'.

You can define this data element + domain yourself or simply replace this code as:

    constants: c_dir_input  type CHAR6 value 'INPUT',
               c_dir_output type CHAR6 value 'OUTPUT'.

**Comment by raungkam** [comment]
Hi @keremkoseoglu 

     Many thanks. I'll try to do this.
